### ISSUE TITLE
NoMethodError - undefined method `to_i' for #<DateTime       

### ISSUE THREAD

**Issue by kokizzu** [thirtyseven/dullard#11]
```
NoMethodError - undefined method `to_i' for #<DateTime:>:
        ~/.gem/ruby/2.1.0/gems/dullard-0.1.0/lib/dullard/reader.rb:234:in `block (2 levels) in rows'
```

the possible correction of that line of code:

```
row << ((shared and value.respond_to? :to_i) ? string_lookup(value.to_i) : value)
```

**Comment by thirtyseven** [comment]
What input sheets are you encountering this on?

**Comment by kokizzu** [comment]
saved xlsx from LibreOffice

**Comment by thirtyseven** [comment]
Can you share the sheet, or another sheet that demonstrates the bug? I am pretty sure I know what the issue is, but having an actual sheet so that I can write a test against it would be very helpful.

**Comment by kokizzu** [comment]
sorry, but no, I already forgotten which cell of the spreadsheet that has
this problem, but I have the workaround, the cell that in date format
stores its date as integer, so what I did was:

```
EPOCH_DATE = Date.new(1899,12,30)
def clean_date date
    return nil if date.nil?
    date.strip!
    return nil if date == '' or date == '-' or date == '0000-00-00'
    return EPOCH_DATE + date.to_i if date == date.to_i.to_s
    # so on
```
